### ISSUE TITLE
It doesn't support authorization code flow

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-python#14]
Only password flow is supported.

https://devcommunity.ringcentral.com/ringcentraldev/topics/glip-bot-with-python

**Comment by grokify** [comment]
For reference, here is a demo app using authorization code with the existing SDK.

https://github.com/ringcentral/ringcentral-demos-oauth/tree/master/python-bottle

**Comment by tylerlong** [comment]
In other SDKs, such as Java, C#...etc. We provide two methods to facilitate authorization code flow:

`authorize_uri(redirect_uri, state)` method returns an uri so that user could be redirected to this uri to start the authorization code flow.

`authorize(auth_code = None, redirect_uri = None)` method exchanges the `auth_code` for token.

It is good if this SDK could provide these two methods. So users don't have to do everything from scratch.

**Comment by kirill-konshin** [comment]
We have an escape latch for this: if you get the tokens you can set them directly via

```python
sdk.platform().auth(). set_data(data)
```

**Comment by grokify** [comment]
Providing support for OAuth 2.0 Authorization Code flow is important because it is a server-based auth flow designed for languages like Python when building websites, e.g. using Django.

In addition to the example code I created and posted above, some Python authorization code for the RingCentral API is built into this community SDK:

https://github.com/tylerlong/ringcentral-python

**Comment by kirill-konshin** [comment]
Fixed in 0.7.8
