### ISSUE TITLE
how set a parameter in SDK builder to not send coverpage

### ISSUE THREAD

**Issue by somatusbs** [ringcentral/ringcentral-python#47]
Hi I am reading through the code and can not figure how to set a parameter in builder to not include the coverpage. Would really appreciate guidance on this.

**Comment by tylerlong** [comment]
For questions, please post to community https://community.ringcentral.com/spaces/8/index.html or create a support ticket: https://developers.ringcentral.com/support/create-case

It is a question instead of issue report. For your question, I think you are talking about fax sending. The answer is to specify `coverIndex: 0` to disable cover page. Please refer to https://github.com/tylerlong/ringcentral-fax-custom-cover-demo
